import type { Club, Fixture, MatchStaff, Player, StandingRow, SupportTicket } from "./types";

// NOTE: All data on this page is mock/sample data for UI development.
// Shapes mirror tpl-backend's Prisma models (Team, Player, Ticket) so wiring
// real API calls in later is a drop-in swap. Fixture/StandingRow/MatchStaff
// have no backend model yet.

// League-wide totals for KPI tiles. In production these come from an
// aggregate query, not from counting the sample arrays below (which only
// hold a handful of illustrative records each).
export const leagueStats = {
  activeClubs: 48,
  activeClubsTrend: "+4 new this month",
  registeredPlayers: 1284,
  registeredPlayersTrend: "+62 this week",
  pendingRegistrations: 12,
  matchesThisWeek: 17,
  prizePool: 85000,
};

export const staffDirectory: MatchStaff[] = [
  { id: "staff-1", fullName: "Michael Osei", role: "REFEREE" },
  { id: "staff-2", fullName: "Julia Tan", role: "COMMISSIONER" },
  { id: "staff-3", fullName: "Lena Carter", role: "REFEREE" },
  { id: "staff-4", fullName: "Ruben Adeyemi", role: "REFEREE" },
  { id: "staff-5", fullName: "Hugo Prentice", role: "COMMISSIONER" },
];

export const clubs: Club[] = [
  {
    id: "club-1",
    name: "Riverside FC",
    code: "RV",
    region: "London North",
    ageGroup: "U19",
    cityOrTown: "London",
    logoUrl: null,
    registrationFeePaid: true,
    registrationFeeStatus: "PAID",
    registrationFeeAmount: 450,
    registrationFeeDate: "2025-08-03",
    playerCount: 24,
    avgAge: 19.4,
    founded: 2015,
    manager: { id: "mgr-1", fullName: "Daniel Pryce", role: "Head Coach", email: "daniel.pryce@riverside.fc", contactNumber: "+44 7700 900001" },
    assignedStaff: [staffDirectory[0], staffDirectory[1]],
    verified: true,
    createdAt: "2025-06-01",
  },
  {
    id: "club-2",
    name: "Camden Rovers",
    code: "CR",
    region: "London East",
    ageGroup: "U19",
    cityOrTown: "London",
    logoUrl: null,
    registrationFeePaid: false,
    registrationFeeStatus: "PENDING",
    registrationFeeAmount: 450,
    registrationFeeDate: null,
    playerCount: 22,
    avgAge: 18.9,
    founded: 2017,
    manager: { id: "mgr-2", fullName: "Liam Kearns", role: "Head Coach", email: "liam.kearns@camden.fc", contactNumber: "+44 7700 900002" },
    assignedStaff: [staffDirectory[2]],
    verified: true,
    createdAt: "2025-06-04",
  },
  {
    id: "club-3",
    name: "Ashford Town",
    code: "AT",
    region: "Surrey",
    ageGroup: "U19",
    cityOrTown: "Ashford",
    logoUrl: null,
    registrationFeePaid: true,
    registrationFeeStatus: "PAID",
    registrationFeeAmount: 450,
    registrationFeeDate: "2025-07-28",
    playerCount: 26,
    avgAge: 19.1,
    founded: 2012,
    manager: { id: "mgr-3", fullName: "Emma Wallace", role: "Head Coach", email: "emma.wallace@ashford.fc", contactNumber: "+44 7700 900003" },
    assignedStaff: [staffDirectory[2], staffDirectory[3]],
    verified: true,
    createdAt: "2025-05-20",
  },
  {
    id: "club-4",
    name: "Highfield United",
    code: "HU",
    region: "Bristol",
    ageGroup: "U19",
    cityOrTown: "Bristol",
    logoUrl: null,
    registrationFeePaid: false,
    registrationFeeStatus: "OVERDUE",
    registrationFeeAmount: 450,
    registrationFeeDate: null,
    playerCount: 21,
    avgAge: 18.7,
    founded: 2019,
    manager: { id: "mgr-4", fullName: "Grace Nolan", role: "Head Coach", email: "grace.nolan@highfield.fc", contactNumber: "+44 7700 900004" },
    assignedStaff: [],
    verified: false,
    createdAt: "2025-08-11",
  },
  {
    id: "club-5",
    name: "Oldbridge FC",
    code: "OB",
    region: "Kent",
    ageGroup: "U19",
    cityOrTown: "Oldbridge",
    logoUrl: null,
    registrationFeePaid: true,
    registrationFeeStatus: "PAID",
    registrationFeeAmount: 450,
    registrationFeeDate: "2025-07-15",
    playerCount: 23,
    avgAge: 19.6,
    founded: 2014,
    manager: { id: "mgr-5", fullName: "Ruth Sanders", role: "Head Coach", email: "ruth.sanders@oldbridge.fc", contactNumber: "+44 7700 900005" },
    assignedStaff: [staffDirectory[1], staffDirectory[4]],
    verified: true,
    createdAt: "2025-05-30",
  },
  {
    id: "club-6",
    name: "Sutton Wanderers",
    code: "SW",
    region: "Surrey",
    ageGroup: "U19",
    cityOrTown: "Sutton",
    logoUrl: null,
    registrationFeePaid: true,
    registrationFeeStatus: "PAID",
    registrationFeeAmount: 450,
    registrationFeeDate: "2025-08-01",
    playerCount: 20,
    avgAge: 18.5,
    founded: 2020,
    manager: { id: "mgr-6", fullName: "Peter Finch", role: "Head Coach", email: "peter.finch@sutton.fc", contactNumber: "+44 7700 900006" },
    assignedStaff: [staffDirectory[0]],
    verified: true,
    createdAt: "2025-06-18",
  },
];

export const players: Player[] = [
  {
    id: "player-1",
    fullName: "Marcus Reid",
    email: "marcus.reid@tplmail.com",
    position: "Striker",
    jerseyNumber: 10,
    dateOfBirth: "2007-03-12",
    nationality: "England",
    teamId: "club-1",
    teamName: "Riverside FC",
    pricingTier: "Elite Showcase",
    scoutGrade: 94,
    attributes: { pace: 91, shooting: 78, passing: 82, dribbling: 88, defending: 45, physical: 74 },
    shirtSize: "L",
    shortsSize: "M",
    sockSize: "Standard",
    medicalConditions: "Left knee monitored following pre-season strain",
    medicalFlags: [
      { label: "Cleared to Play", severity: "OK" },
      { label: "Left Knee — Monitor", severity: "WARNING" },
      { label: "Concussion Protocol Clear", severity: "OK" },
    ],
    isMvpFeatured: true,
    scoutNote:
      "Explosive off the mark with excellent close control under pressure. Composure in the final third stands out for his age group — ready for regional trial fixtures.",
    scoutedBy: "Julia Tan",
    scoutedAt: "2026-08-14",
  },
  {
    id: "player-2",
    fullName: "Dele Osei",
    email: "dele.osei@tplmail.com",
    position: "Central Midfield",
    jerseyNumber: 8,
    dateOfBirth: "2006-11-02",
    nationality: "England",
    teamId: "club-3",
    teamName: "Ashford Town",
    pricingTier: "Premium Exposure",
    scoutGrade: 91,
    attributes: { pace: 76, shooting: 71, passing: 90, dribbling: 84, defending: 68, physical: 79 },
    shirtSize: "M",
    shortsSize: "M",
    sockSize: "Standard",
    medicalConditions: null,
    medicalFlags: [{ label: "Cleared to Play", severity: "OK" }],
    isMvpFeatured: false,
    scoutNote: "Metronomic passer who dictates tempo. Needs work tracking back but reads the game a year ahead of his peers.",
    scoutedBy: "Hugo Prentice",
    scoutedAt: "2026-08-10",
  },
  {
    id: "player-3",
    fullName: "Sam Whitlock",
    email: "sam.whitlock@tplmail.com",
    position: "Centre Back",
    jerseyNumber: 4,
    dateOfBirth: "2007-01-22",
    nationality: "Wales",
    teamId: "club-2",
    teamName: "Camden Rovers",
    pricingTier: "Standard",
    scoutGrade: 88,
    attributes: { pace: 68, shooting: 42, passing: 74, dribbling: 55, defending: 89, physical: 86 },
    shirtSize: "XL",
    shortsSize: "L",
    sockSize: "Standard",
    medicalConditions: null,
    medicalFlags: [{ label: "Cleared to Play", severity: "OK" }],
    isMvpFeatured: false,
    scoutNote: "Commanding in the air, rarely beaten one-on-one. Distribution under pressure is the next development target.",
    scoutedBy: "Julia Tan",
    scoutedAt: "2026-08-05",
  },
  {
    id: "player-4",
    fullName: "Kofi Mensah",
    email: "kofi.mensah@tplmail.com",
    position: "Right Wing",
    jerseyNumber: 7,
    dateOfBirth: "2007-06-18",
    nationality: "Ghana",
    teamId: "club-5",
    teamName: "Oldbridge FC",
    pricingTier: "Premium Exposure",
    scoutGrade: 86,
    attributes: { pace: 93, shooting: 74, passing: 70, dribbling: 89, defending: 38, physical: 66 },
    shirtSize: "M",
    shortsSize: "S",
    sockSize: "Standard",
    medicalConditions: null,
    medicalFlags: [{ label: "Cleared to Play", severity: "OK" }],
    isMvpFeatured: true,
    scoutNote: "Frightening pace in transition. Final ball is inconsistent but the raw tools are top-percentile for the league.",
    scoutedBy: "Hugo Prentice",
    scoutedAt: "2026-08-02",
  },
  {
    id: "player-5",
    fullName: "James Cole",
    email: "james.cole@tplmail.com",
    position: "Goalkeeper",
    jerseyNumber: 1,
    dateOfBirth: "2006-09-09",
    nationality: "England",
    teamId: "club-4",
    teamName: "Highfield United",
    pricingTier: "Standard",
    scoutGrade: 83,
    attributes: { pace: 55, shooting: 30, passing: 62, dribbling: 40, defending: 58, physical: 80 },
    shirtSize: "L",
    shortsSize: "L",
    sockSize: "Standard",
    medicalConditions: null,
    medicalFlags: [{ label: "Cleared to Play", severity: "OK" }],
    isMvpFeatured: false,
    scoutNote: "Excellent shot-stopper with strong command of the box. Distribution with feet still developing.",
    scoutedBy: "Julia Tan",
    scoutedAt: "2026-07-29",
  },
  {
    id: "player-6",
    fullName: "Tunde Okafor",
    email: "tunde.okafor@tplmail.com",
    position: "Left Back",
    jerseyNumber: 3,
    dateOfBirth: "2007-04-30",
    nationality: "Nigeria",
    teamId: "club-6",
    teamName: "Sutton Wanderers",
    pricingTier: "Standard",
    scoutGrade: 81,
    attributes: { pace: 84, shooting: 52, passing: 73, dribbling: 71, defending: 75, physical: 72 },
    shirtSize: "M",
    shortsSize: "M",
    sockSize: "Standard",
    medicalConditions: null,
    medicalFlags: [{ label: "Cleared to Play", severity: "OK" }],
    isMvpFeatured: false,
    scoutNote: "Overlaps with good timing and recovers well. Needs to add end product to his final third work.",
    scoutedBy: "Hugo Prentice",
    scoutedAt: "2026-07-25",
  },
  {
    id: "player-7",
    fullName: "Noah Pierce",
    email: "noah.pierce@tplmail.com",
    position: "Central Midfield",
    jerseyNumber: 6,
    dateOfBirth: "2006-12-14",
    nationality: "England",
    teamId: "club-1",
    teamName: "Riverside FC",
    pricingTier: "Standard",
    scoutGrade: 79,
    attributes: { pace: 70, shooting: 60, passing: 78, dribbling: 69, defending: 72, physical: 76 },
    shirtSize: "L",
    shortsSize: "M",
    sockSize: "Standard",
    medicalConditions: null,
    medicalFlags: [{ label: "Cleared to Play", severity: "OK" }],
    isMvpFeatured: false,
    scoutNote: "Reliable box-to-box engine. Consistency across 90 minutes is his strongest asset right now.",
    scoutedBy: "Julia Tan",
    scoutedAt: "2026-07-20",
  },
];

export const fixtures: Fixture[] = [
  {
    id: "fx-1",
    homeClubId: "club-1",
    awayClubId: "club-2",
    kickoff: "2026-08-20T15:00:00Z",
    venue: "Riverside Park",
    pitch: "Pitch 1",
    refereeId: "staff-1",
    commissionerId: "staff-2",
    status: "LIVE",
    homeScore: 2,
    awayScore: 1,
    minute: 67,
    goals: [
      { id: "g-1", fixtureId: "fx-1", clubId: "club-1", scorerName: "Marcus Reid", minute: 24, type: "REGULAR" },
      { id: "g-2", fixtureId: "fx-1", clubId: "club-2", scorerName: "Sam Whitlock", minute: 41, type: "REGULAR" },
      { id: "g-3", fixtureId: "fx-1", clubId: "club-1", scorerName: "Noah Pierce", minute: 58, type: "REGULAR" },
    ],
    cards: [
      { id: "c-1", fixtureId: "fx-1", clubId: "club-2", playerName: "Sam Whitlock", minute: 38, cardType: "YELLOW", reason: "Tactical Foul" },
      { id: "c-2", fixtureId: "fx-1", clubId: "club-1", playerName: "Marcus Reid", minute: 65, cardType: "YELLOW", reason: "Dissent" },
    ],
  },
  {
    id: "fx-2",
    homeClubId: "club-3",
    awayClubId: "club-4",
    kickoff: "2026-08-20T15:00:00Z",
    venue: "Ashford Grounds",
    pitch: "Pitch 3",
    refereeId: "staff-3",
    commissionerId: null,
    status: "LIVE",
    homeScore: 0,
    awayScore: 0,
    minute: 34,
    goals: [],
    cards: [],
  },
  {
    id: "fx-3",
    homeClubId: "club-5",
    awayClubId: "club-6",
    kickoff: "2026-08-22T18:00:00Z",
    venue: "Oldbridge Arena",
    pitch: "Pitch 2",
    refereeId: "staff-4",
    commissionerId: null,
    status: "SCHEDULED",
    homeScore: null,
    awayScore: null,
    minute: null,
    goals: [],
    cards: [],
  },
  {
    id: "fx-4",
    homeClubId: "club-2",
    awayClubId: "club-1",
    kickoff: "2026-08-22T20:15:00Z",
    venue: "Camden Ground",
    pitch: "Pitch 1",
    refereeId: null,
    commissionerId: null,
    status: "SCHEDULED",
    homeScore: null,
    awayScore: null,
    minute: null,
    goals: [],
    cards: [],
  },
  {
    id: "fx-5",
    homeClubId: "club-3",
    awayClubId: "club-6",
    kickoff: "2026-08-17T17:00:00Z",
    venue: "Ashford Grounds",
    pitch: "Pitch 1",
    refereeId: "staff-2",
    commissionerId: null,
    status: "FULL_TIME",
    homeScore: 3,
    awayScore: 2,
    minute: null,
    goals: [
      { id: "g-4", fixtureId: "fx-5", clubId: "club-3", scorerName: "Dele Osei", minute: 14, type: "REGULAR" },
      { id: "g-5", fixtureId: "fx-5", clubId: "club-6", scorerName: "Tunde Okafor", minute: 30, type: "REGULAR" },
      { id: "g-6", fixtureId: "fx-5", clubId: "club-3", scorerName: "Dele Osei", minute: 52, type: "PENALTY" },
      { id: "g-7", fixtureId: "fx-5", clubId: "club-6", scorerName: "Leo Clarke", minute: 74, type: "REGULAR" },
      { id: "g-8", fixtureId: "fx-5", clubId: "club-3", scorerName: "Ethan Brooks", minute: 88, type: "REGULAR" },
    ],
    cards: [
      { id: "c-3", fixtureId: "fx-5", clubId: "club-6", playerName: "Tunde Okafor", minute: 44, cardType: "YELLOW", reason: "Reckless Tackle" },
      { id: "c-4", fixtureId: "fx-5", clubId: "club-6", playerName: "Leo Clarke", minute: 82, cardType: "RED", reason: "Violent Conduct" },
    ],
  },
  {
    id: "fx-6",
    homeClubId: "club-1",
    awayClubId: "club-5",
    kickoff: "2026-08-17T15:00:00Z",
    venue: "Riverside Park",
    pitch: "Pitch 1",
    refereeId: "staff-1",
    commissionerId: null,
    status: "FULL_TIME",
    homeScore: 1,
    awayScore: 1,
    minute: null,
    goals: [
      { id: "g-9", fixtureId: "fx-6", clubId: "club-1", scorerName: "Marcus Reid", minute: 61, type: "REGULAR" },
      { id: "g-10", fixtureId: "fx-6", clubId: "club-5", scorerName: "Kofi Mensah", minute: 79, type: "REGULAR" },
    ],
    cards: [],
  },
];

export const standings: StandingRow[] = [
  { position: 1, clubId: "club-1", played: 14, won: 10, drawn: 2, lost: 2, goalsFor: 32, goalsAgainst: 12, pointsPenalty: 0, points: 32, form: ["W", "W", "W", "D", "W"], zone: "PROMOTION" },
  { position: 2, clubId: "club-3", played: 14, won: 9, drawn: 3, lost: 2, goalsFor: 28, goalsAgainst: 14, pointsPenalty: 0, points: 30, form: ["W", "W", "D", "W", "L"], zone: "PROMOTION" },
  { position: 3, clubId: "club-5", played: 14, won: 8, drawn: 4, lost: 2, goalsFor: 25, goalsAgainst: 15, pointsPenalty: 0, points: 28, form: ["D", "W", "W", "W", "D"], zone: null },
  { position: 4, clubId: "club-2", played: 14, won: 7, drawn: 4, lost: 3, goalsFor: 24, goalsAgainst: 18, pointsPenalty: 0, points: 25, form: ["W", "L", "W", "D", "W"], zone: null },
  { position: 5, clubId: "club-4", played: 14, won: 5, drawn: 4, lost: 5, goalsFor: 18, goalsAgainst: 19, pointsPenalty: 3, points: 16, form: ["L", "D", "W", "L", "D"], zone: null },
  { position: 6, clubId: "club-6", played: 14, won: 4, drawn: 3, lost: 7, goalsFor: 17, goalsAgainst: 25, pointsPenalty: 0, points: 15, form: ["L", "W", "D", "L", "L"], zone: "RELEGATION" },
];

export const supportTickets: SupportTicket[] = [
  {
    id: "tk-1",
    ticketNumber: 1042,
    subject: "Referee no-show at Pitch 2",
    category: "MATCH_SCHEDULE",
    status: "IN_PROGRESS",
    priority: "URGENT",
    requesterName: "Daniel Pryce",
    requesterRole: "Team Manager",
    clubName: "Riverside FC",
    createdAt: "2026-08-20T14:18:00Z",
    updatedAt: "2026-08-20T14:25:00Z",
    messages: [
      { id: "m1", ticketId: "tk-1", message: "Our referee didn't show up for the 3pm fixture at Pitch 2. We need someone assigned ASAP — kickoff is in 40 minutes.", createdAt: "2026-08-20T14:18:00Z", senderName: "Daniel Pryce", isAdmin: false },
      { id: "m2", ticketId: "tk-1", message: "Thanks for flagging this, Daniel. I'm reaching out to our backup referee pool right now.", createdAt: "2026-08-20T14:20:00Z", senderName: "Alex Whitfield", isAdmin: true },
      { id: "m3", ticketId: "tk-1", message: "Appreciate it. Let me know as soon as you have someone confirmed.", createdAt: "2026-08-20T14:21:00Z", senderName: "Daniel Pryce", isAdmin: false },
      { id: "m4", ticketId: "tk-1", message: "Michael Osei is available and en route to Riverside Park now. ETA 25 minutes.", createdAt: "2026-08-20T14:24:00Z", senderName: "Alex Whitfield", isAdmin: true },
      { id: "m5", ticketId: "tk-1", message: "Perfect, that works. Thank you for the quick turnaround!", createdAt: "2026-08-20T14:25:00Z", senderName: "Daniel Pryce", isAdmin: false },
    ],
  },
  {
    id: "tk-2",
    ticketNumber: 1041,
    subject: "Kit size correction needed",
    category: "EQUIPMENT",
    status: "OPEN",
    priority: "NORMAL",
    requesterName: "Marcus Reid",
    requesterRole: "Player",
    clubName: "Riverside FC",
    createdAt: "2026-08-20T13:02:00Z",
    updatedAt: "2026-08-20T13:02:00Z",
    messages: [
      { id: "m6", ticketId: "tk-2", message: "Can you update my jersey to size L? The M I was issued is too tight for training.", createdAt: "2026-08-20T13:02:00Z", senderName: "Marcus Reid", isAdmin: false },
    ],
  },
  {
    id: "tk-3",
    ticketNumber: 1038,
    subject: "Registration fee not reflecting",
    category: "REGISTRATION",
    status: "OPEN",
    priority: "NORMAL",
    requesterName: "Liam Kearns",
    requesterRole: "Team Manager",
    clubName: "Camden Rovers",
    createdAt: "2026-08-20T11:40:00Z",
    updatedAt: "2026-08-20T11:40:00Z",
    messages: [
      { id: "m7", ticketId: "tk-3", message: "We paid the registration fee on Tuesday but the club status still shows pending. Can you check the payment reference?", createdAt: "2026-08-20T11:40:00Z", senderName: "Liam Kearns", isAdmin: false },
    ],
  },
  {
    id: "tk-4",
    ticketNumber: 1035,
    subject: "Player transfer request",
    category: "OTHERS",
    status: "OPEN",
    priority: "URGENT",
    requesterName: "Tunde Okafor",
    requesterRole: "Player",
    clubName: "Sutton Wanderers",
    createdAt: "2026-08-19T10:15:00Z",
    updatedAt: "2026-08-19T10:15:00Z",
    messages: [
      { id: "m8", ticketId: "tk-4", message: "I'd like to request a transfer to a club closer to home for the second half of the season.", createdAt: "2026-08-19T10:15:00Z", senderName: "Tunde Okafor", isAdmin: false },
    ],
  },
  {
    id: "tk-5",
    ticketNumber: 1033,
    subject: "Access issue — team portal",
    category: "GENERAL",
    status: "OPEN",
    priority: "NORMAL",
    requesterName: "Emma Wallace",
    requesterRole: "Team Manager",
    clubName: "Ashford Town",
    createdAt: "2026-08-19T09:05:00Z",
    updatedAt: "2026-08-19T09:05:00Z",
    messages: [
      { id: "m9", ticketId: "tk-5", message: "Getting an error when I try to log in to the team portal since this morning.", createdAt: "2026-08-19T09:05:00Z", senderName: "Emma Wallace", isAdmin: false },
    ],
  },
  {
    id: "tk-6",
    ticketNumber: 1029,
    subject: "MVP nomination query",
    category: "GENERAL",
    status: "RESOLVED",
    priority: "NORMAL",
    requesterName: "Julia Tan",
    requesterRole: "Commissioner",
    clubName: null,
    createdAt: "2026-08-17T09:00:00Z",
    updatedAt: "2026-08-17T12:00:00Z",
    messages: [
      { id: "m10", ticketId: "tk-6", message: "Just confirming the nomination deadline for this matchday's MVP spotlight.", createdAt: "2026-08-17T09:00:00Z", senderName: "Julia Tan", isAdmin: false },
      { id: "m11", ticketId: "tk-6", message: "Deadline is Sunday 11:59pm — nominations open on the Players & Scouting page.", createdAt: "2026-08-17T12:00:00Z", senderName: "Alex Whitfield", isAdmin: true },
    ],
  },
];

export function getClub(id: string): Club | undefined {
  return clubs.find((c) => c.id === id);
}

export function getStaff(id?: string | null): MatchStaff | undefined {
  if (!id) return undefined;
  return staffDirectory.find((s) => s.id === id);
}
